# action.yml
name: 'Sync Code'
description: 'Sync between alicode and github'
inputs:
  git_source:  # id of input
    description: 'git url of source repo'
    required: true
    default: ''
  git_source_key:  # id of input
    description: 'key of source repo'
    required: true
    default: ''
  git_remote:  # id of input
    description: 'git url of remote repo'
    required: true
    default: ''
  git_remote_key:  # id of input
    description: 'key of remote repo'
    required: true
    default: ''
outputs:
  sync_code: # id of output
    description: 'The sync code'
  sync_result: # id of output
    description: 'The sync result'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.git_source }} ${{ inputs.git_source_key }}  ${{ inputs.git_remote }}  ${{ inputs.git_remote_key }}
 